CREATE TABLE AIRFLOW_COMMITS (
  COMMIT_SHA VARCHAR(500),
  COMMIT_URL VARCHAR(5000),
  COMMIT_MESSAGE VARCHAR(5000),
  COMMIT_DATE DATE,
  AUTHOR_ID INTEGER,
  CREATION_DATE DATE
);

CREATE TABLE AIRFLOW_AUTHOR (
  ID INTEGER,
  LOGIN_NAME VARCHAR(50),
  EMAIL VARCHAR(150),
  EMAIL_COMPANY VARCHAR(150),
  CREATION_DATE DATE
);
